### PR TITLE
Fix #12154

### PR DESCRIPTION
**Pull request by alexshepherd-hydrant**
Fix for Bug #12154 - http://projects.theforeman.org/issues/12154

### CODE REVIEW

**Comment by shlomizadok** [comment]
@alexshepherd-hydrant - can you please reword the commit message to add more descriptive solution of the issue. e.g., something like: `Fixes #12154 - Adds uuid....`

**Comment by alexshepherd-hydrant** [comment]
@shlomizadok Done, thanks.

**Comment by dLobatog** [comment]
Merged as d4519974f765ce344c5f1cb8120da7afbd12ed81, thanks @alexshepherd-hydrant !

I'll release foreman-digitalocean 0.2.1 tomorrow with this patch.

**Comment by TJM** [comment]
Thanks @dLobatog !

**Pull request closed without merging**
